
---
environment: production
chdir: .
address: 127.0.0.1
user: robinhoode
group: robinhoode
port: 1234
pid: thin.pid
rackup: config.ru
log: thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true